on:
  push:
    branches:
      - main

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: reports
          path: plugin/build/reports
